"""Triage agent for classifying incoming log events."""

import logging

from langchain_core.prompts import ChatPromptTemplate
from langchain_openai import ChatOpenAI
from pydantic import BaseModel, Field

from src.core.config import settings
from src.models.schemas import AttackType, LogEvent, RecommendedAction, SeverityLevel

# Set up logging
logger = logging.getLogger(__name__)

# System prompt for the triage agent
SYSTEM_PROMPT = """You are an expert Security Operations Center (SOC) analyst with 10 years of experience in network intrusion detection.
Analyze the provided network log event and classify it accurately into a structured incident report.
Be concise but thorough in your reasoning. Look for indicators of compromise (IoC) and anomalous patterns.
Your output must perfectly map to the requested structured JSON schema."""


class LLMOutput(BaseModel):
    """Model representing the structured output from the LLM."""

    attack_type: AttackType
    severity: SeverityLevel
    confidence_score: float = Field(ge=0.0, le=1.0)
    recommended_action: RecommendedAction
    reasoning: str
    indicators: list[str]


def analyze_log_event(log_event: LogEvent) -> dict:
    """Analyze a log event using the LLM triage agent and return a partial incident report.

    Args:
        log_event (LogEvent): The raw log event to analyze.

    Returns:
        dict: Partially filled incident report data generated by the LLM.
    """
    logger.info("Initializing triage agent for log event from %s", log_event.source_ip)

    # Initialize the LLM with structured output
    llm = ChatOpenAI(
        model="gpt-4o-mini",
        temperature=0,
        api_key=settings.OPENAI_API_KEY,
    )

    structured_llm = llm.with_structured_output(LLMOutput)

    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", SYSTEM_PROMPT),
            ("human", "Log Event to analyze:\n{log_json}"),
        ]
    )

    chain = prompt | structured_llm

    # Run the chain
    logger.debug("Running LLM analysis on log event: %s", log_event.event_type)
    result = chain.invoke({"log_json": log_event.model_dump_json()})

    return result.model_dump()
